let books = [
    { Title: "Cien años de soledad", Genre: "Novela", Author: ["Gabriel García Márquez"], Pages: 417, Published: "1967-06-05", Read: false, Website: "https://www.bibliofilia.org/cien-anos-de-soledad" },
    { Title: "Don Quijote de la Mancha", Genre: "Novela", Author: ["Miguel de Cervantes"], Pages: 1023, Published: "1605-01-16", Read: true, Website: "https://www.cervantesvirtual.com/obra-visor/don-quijote-de-la-mancha--0/html/ff04130b-82b1-4f44-b9e5-4ed8e682dbe2_2.html" },
    { Title: "Orgullo y prejuicio", Genre: "Romance", Author: ["Jane Austen"], Pages: 279, Published: "1813-01-28", Read: false, Website: "https://www.janeausten.co.uk/orgullo-y-prejuicio" },
    { Title: "Cuentos de la selva", Genre: "Cuentos", Author: ["Horacio Quiroga", "Gabriel García Márquez"], Pages: 120, Published: "1918-01-01", Read: false, Website: "https://www.leer.com.ar/cuentos-de-la-selva" },
    { Title: "Relatos de la guerra civil española", Genre: "Antología", Author: ["Carmen Laforet", "Rafael Sánchez Ferlosio", "Antonio Buero Vallejo"], Pages: 320, Published: "1970-01-01", Read: true, Website: "https://www.culturamas.es/2020/04/04/relatos-de-la-guerra-civil-espanola/" },
    { Title: "1984", Genre: "Distopía", Author: ["George Orwell"], Pages: 328, Published: "1949-06-08", Read: true, Website: "https://www.george-orwell.org/1984" },
    { Title: "El gran Gatsby", Genre: "Novela", Author: ["F. Scott Fitzgerald"], Pages: 180, Published: "1925-04-10", Read: false, Website: "https://www.fsgbooks.com/the-great-gatsby" },
    { Title: "Crónica de una muerte anunciada", Genre: "Novela", Author: ["Gabriel García Márquez"], Pages: 120, Published: "1981-09-01", Read: true, Website: "https://www.librosdelzorro.com/cronica-de-una-muerte-anunciada" },
    { Title: "Antología poética", Genre: "Poesía", Author: ["Pablo Neruda", "Gabriela Mistral", "Jorge Luis Borges"], Pages: 400, Published: "2000-01-01", Read: false, Website: "https://www.poetryfoundation.org/poets/pablo-neruda" },
    { Title: "Literatura argentina contemporánea", Genre: "Antología", Author: ["Julio Cortázar", "Adolfo Bioy Casares", "Silvina Ocampo"], Pages: 350, Published: "1995-01-01", Read: false, Website: "https://www.letraslibres.com/revista/literatura-argentina-contemporanea" },
    { Title: "Cuentos completos", Genre: "Cuentos", Author: ["Jorge Luis Borges", "Adolfo Bioy Casares"], Pages: 1040, Published: "1974-01-01", Read: false, Website: "https://www.borges.com.ar/cuentos-completos" },
    { Title: "Poemas de amor", Genre: "Poesía", Author: ["Pablo Neruda", "Mario Benedetti", "Joaquín Gallegos Lara"], Pages: 250, Published: "1980-01-01", Read: true, Website: "https://www.poemario.com/poemas-de-amor" },
    { Title: "Moby Dick", Genre: "Aventura", Author: ["Herman Melville"], Pages: 585, Published: "1851-10-18", Read: false, Website: "https://www.hermanmelville.org/moby-dick" },
    { Title: "En busca del tiempo perdido", Genre: "Novela", Author: ["Marcel Proust"], Pages: 4215, Published: "1913-11-14", Read: false, Website: "https://www.proust.com/en-busca-del-tiempo-perdido" },
    { Title: "El proceso", Genre: "Ficción", Author: ["Franz Kafka"], Pages: 254, Published: "1925-04-26", Read: false, Website: "https://www.kafka.org/el-proceso" },
    { Title: "El túnel", Genre: "Novela", Author: ["Ernesto Sabato"], Pages: 288, Published: "1948-01-01", Read: true, Website: "https://www.sabato.com/el-tunel" },
    { Title: "La sombra del viento", Genre: "Novela", Author: ["Carlos Ruiz Zafón"], Pages: 487, Published: "2001-04-17", Read: true, Website: "https://www.zafon.com/la-sombra-del-viento" },
    { Title: "Los miserables", Genre: "Novela", Author: ["Victor Hugo"], Pages: 1463, Published: "1862-04-03", Read: false, Website: "https://www.lesmiserables.com" },
    { Title: "Cumbres borrascosas", Genre: "Novela", Author: ["Emily Brontë"], Pages: 400, Published: "1847-12-30", Read: false, Website: "https://www.bronte.org.uk/cumbres-borrascosas" },
    { Title: "El amor en los tiempos del cólera", Genre: "Novela", Author: ["Gabriel García Márquez"], Pages: 368, Published: "1985-03-06", Read: true, Website: "https://www.librosdelzorro.com/el-amor-en-los-tiempos-del-colera" },
    { Title: "Fahrenheit 451", Genre: "Ciencia ficción", Author: ["Ray Bradbury"], Pages: 158, Published: "1953-10-19", Read: true, Website: "https://www.raybradbury.com/fahrenheit-451" },
    { Title: "El guardián entre el centeno", Genre: "Novela", Author: ["J.D. Salinger"], Pages: 277, Published: "1951-07-16", Read: true, Website: "https://www.salinger.com/el-guardian-entre-el-centeno" },
    { Title: "El viejo y el mar", Genre: "Novela", Author: ["Ernest Hemingway"], Pages: 127, Published: "1952-09-01", Read: false, Website: "https://www.hemingway.com/el-viejo-y-el-mar" },
    { Title: "Un mundo feliz", Genre: "Ciencia ficción", Author: ["Aldous Huxley"], Pages: 268, Published: "1932-01-01", Read: false, Website: "https://www.huxley.com/un-mundo-feliz" },
    { Title: "Las uvas de la ira", Genre: "Novela", Author: ["John Steinbeck"], Pages: 464, Published: "1939-04-14", Read: true, Website: "https://www.steinbeck.org/las-uvas-de-la-ira" },
    { Title: "El retrato de Dorian Gray", Genre: "Novela", Author: ["Oscar Wilde"], Pages: 254, Published: "1890-07-01", Read: false, Website: "https://www.wilde.com/el-retrato-de-dorian-gray" }
];